apiVersion: v1
kind: Service
metadata:
    labels:
      app: mywebd
    name: mywebd
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mywebd
  type: LoadBalancer

